[2018-07-17 21:25:49.044422] [INFO] [ddt_case.py] [setUp] [17] 测试用例开始执行
[2018-07-17 21:25:49.077423] [INFO] [ddt_case.py] [test_api] [27] 读取请求参数：url:{'securityToken': 'c063c4d327282264257d60163da3a33e';'username': '88@qq.com';'password': '111111';'remember': 1},key:login,canshu:,postorget:POST
[2018-07-17 21:25:49.117426] [INFO] [test_requests.py] [post] [29] post请求出错原因:No connection adapters were found for '{'securityToken': 'c063c4d327282264257d60163da3a33e';'username': '88@qq.com';'password': '111111';'remember': 1}'
[2018-07-17 21:25:49.120426] [INFO] [ddt_case.py] [test_api] [31] 返回结果:{'code': 1, 'result': "post请求出错原因:No connection adapters were found for '{'securityToken': 'c063c4d327282264257d60163da3a33e';'username': '88@qq.com';'password': '111111';'remember': 1}'"}
[2018-07-17 21:25:49.123426] [INFO] [panduan.py] [assertre] [29] 测试预期值2
[2018-07-17 21:25:49.124426] [INFO] [ddt_case.py] [tearDown] [19] 测试用例执行完毕
